version: "2.2"
services:
  mysql:
    image: mysql:${MYSQL_VERSION}
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    mem_limit: ${MEM_LIMIT}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - mysql:/var/lib/mysql
      - mysql-files:/var/lib/mysql-files
      - mysql-config:/etc/mysql
    security_opt:
      - seccomp:unconfined
  redis:
    restart: always
    image: redis:${REDIS_VERSION}
    command: redis-server
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis:/data
volumes:
  redis:
    driver: local
  mysql:
    driver: local
  mysql-files:
    driver: local
  mysql-config:
    driver: local