@startuml
class com.rare_earth_track.admin.controller.RetFactoryController {
- RetFactoryService factoryService
+ CommonResult<List<RetFactory>> list(Integer,Integer)
+ CommonResult<String> addFactory(RetFactoryParam)
+ CommonResult<String> deleteFactory(String)
+ CommonResult<String> updateFactory(String,RetFactoryParam)
+ CommonResult<String> inviteUser(String,String,String)
+ CommonResult<List<RetFactory>> getFactory(RetFactory)
+ CommonResult<List<RetMember>> listMembers(Integer,Integer,String)
+ CommonResult<String> deleteMember(String,String)
+ CommonResult<String> updateMemberJob(String,String,RetMemberParam)
+ CommonResult<String> handleInvitation(String,String)
+ CommonResult<List<RetProduct>> listProducts(String)
}
class com.rare_earth_track.admin.controller.RetProductController {
- RetProductService productService
+ CommonResult<List<RetProduct>> list(Integer,Integer)
}
class com.rare_earth_track.admin.controller.RetResourceController {
- RetResourceService resourceService
+ CommonResult<CommonPage<RetResource>> list(Integer,Integer)
+ CommonResult<String> addResource(RetResourceParam)
+ CommonResult<String> updateResource(String,RetResourceParam)
+ CommonResult<String> delResource(String)
}
class com.rare_earth_track.admin.controller.RetUserController {
- RetUserService userService
+ CommonResult<CommonPage<RetUser>> list(Integer,Integer)
+ CommonResult<RetUser> getUser(String)
+ CommonResult<RetUser> getUser(Map<String,String>)
+ CommonResult<List<RetUser>> getUserByUserParam(RetUser)
+ CommonResult<String> updateUser(RetUser,Map<String,String>)
+ CommonResult<String> updateUser(RetUser)
+ CommonResult<RetUser> updateUserRole(Long,Long)
+ CommonResult<String> deleteUser(Long)
}
class com.rare_earth_track.admin.controller.RetRoleController {
- RetRoleService roleService
- RetRoleResourceRelationService resourceRoleRelationService
+ CommonResult<String> insertRoleResource(String,String)
+ CommonResult<CommonPage<RetResource>> listRoleResources(String,Integer,Integer)
+ CommonResult<String> deleteRoleResource(String,String)
+ CommonResult<String> addRole(RetRoleParam)
+ CommonResult<CommonPage<RetRole>> list(Integer,Integer)
+ CommonResult<String> delRole(String)
+ CommonResult<String> updateRole(String,RetRoleParam)
}
class com.rare_earth_track.admin.controller.RetAdminController {
- RetUserService userService
- JwtSecurityProperties properties
- RetUserAuthService userAuthService
- RetMailService mailService
+ CommonResult<String> unbindUserAuth(IdentifyType,Map<String,String>)
+ CommonResult<String> updateUsername(Map<String,String>,String)
+ CommonResult<String> updateUserPassword(RetUpdateUserPasswordParam)
+ CommonResult<Map<String,String>> login(RetLoginParam)
+ CommonResult<String> register(RetUserRegisterParam)
+ CommonResult<String> logout(Map<String,String>)
+ CommonResult<String> updateUserAuth(Long,IdentifyType,RetUserAuthParam)
+ CommonResult<Map<String,String>> refreshToken(HttpServletRequest)
+ CommonResult<String> generateAuthCode(IdentifyType,String)
}
class com.rare_earth_track.admin.controller.RetMemberJobController {
- RetMemberJobService memberJobService
+ CommonResult<List<RetMemberJob>> list(Integer,Integer)
+ CommonResult<List<RetPermission>> listJobPermissions(Integer,Integer,Long)
+ CommonResult<String> addJobResource(String,String)
+ CommonResult<String> deleteJobResource(String,String)
}
class com.rare_earth_track.admin.controller.RetMemberController {
- RetMemberService factoryService
+ CommonResult<List<RetMember>> list(Integer,Integer)
}
@enduml