version: "3.9"

services:
  web:
    depends_on:
      - admin
      - portal
    image: nginx:1.21.6
    ports:
      - ${RARE_EARTH_TRACK_WEB}:80
    volumes:
      - /data/uploads:/data/uploads
      - web-data:/usr/share/nginx/html/release
      - ./default.conf:/etc/nginx/conf.d/default.conf
  web-portal-setup:
    depends_on:
      - web
    image: hhoao/ret-web-portal-setup:${RARE_EARTH_TRACK_WEB_PORTAL_VERSION}
    tty: true
    command: >
      sh -c "
        if [ -d /usr/share/nginx/html/release/portal ]; then
          rm -rf /usr/share/nginx/html/release/portal;
        fi;
        mkdir /usr/share/nginx/html/release/portal;
        cp -r /data/* /usr/share/nginx/html/release/portal"
    volumes:
      - web-data:/usr/share/nginx/html/release
  web-admin-setup:
    image: hhoao/ret-web-admin-setup:${RARE_EARTH_TRACK_WEB_ADMIN_VERSION}
    depends_on:
      - web
    command: >
      sh -c "
        if [ -d /usr/share/nginx/html/release/admin ]; then
          rm -rf /usr/share/nginx/html/release/admin;
          echo portal existed;
        fi;
        mkdir /usr/share/nginx/html/release/admin;
        cp -r /data/* /usr/share/nginx/html/release/admin"
    volumes:
      - web-data:/usr/share/nginx/html/release
  portal:
    image: hhoao/rare-earth-track-portal:${RARE_EARTH_TRACK_PORTAL_VERSION}
    environment:
      - JASYPT_PASSWORD=${JASYPT_PASSWORD}
    volumes:
      - /data/uploads:/data/uploads
    ports:
      - ${RARE_EARTH_TRACK_PORTAL_PORT}:8889

  admin:
    image: hhoao/rare-earth-track-admin:${RARE_EARTH_TRACK_ADMIN_VERSION}
    environment:
      - JASYPT_PASSWORD=${JASYPT_PASSWORD}
    volumes:
      - /data/uploads:/data/uploads
    ports:
      - ${RARE_EARTH_TRACK_ADMIN_PORT}:8888

  filebeat:
    image: ${FILEBEAT_IMAGE_NAME}:${FILEBEAT_IMAGE_VERSION}
    user: "0"
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    volumes:
      - type: volume
        source: es-certs
        target: /usr/share/filebeat/config/certs
      - type: bind
        source: /var/lib/docker/containers
        target: /var/lib/docker/containers
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: filebeat.yml
        target: /usr/share/filebeat/filebeat.yml
  logstash:
    image: ${LOGSTASH_IMAGE_NAME}:${LOGSTASH_IMAGE_VERSION}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - MYSQL_HOSTS=mysql:3306
      - ES_HOSTS=https://es01:9200
    volumes:
      - es-certs:/data/elastic

volumes:
  es-certs:
    driver: local
  web-data:
    driver: local
