version: "2.2"
services:
  web:
    depends_on:
      - admin
      - portal
    image: nginx:1.21.6
    ports:
      - ${RARE_EARTH_TRACK_WEB}:80
    volumes:
      - /data/uploads:/data/uploads
      - web-data:/usr/share/nginx/html/release
      - ./default.conf:/etc/nginx/conf.d/default.conf
  web-portal-setup:
    depends_on:
      - web
    image: hhoao/ret-web-portal-setup:${RARE_EARTH_TRACK_WEB_PORTAL_VERSION}
    tty: true
    command: >
      sh -c "
        if [ -d /usr/share/nginx/html/release/portal ]; then
          rm -rf /usr/share/nginx/html/release/portal;
        fi;
        mkdir /usr/share/nginx/html/release/portal;
        cp -r /data/* /usr/share/nginx/html/release/portal"
    volumes:
      - web-data:/usr/share/nginx/html/release
  web-admin-setup:
    image: hhoao/ret-web-admin-setup:${RARE_EARTH_TRACK_WEB_ADMIN_VERSION}
    depends_on:
      - web
    command: >
      sh -c "
        if [ -d /usr/share/nginx/html/release/admin ]; then
          rm -rf /usr/share/nginx/html/release/admin;
          echo portal existed;
        fi;
        mkdir /usr/share/nginx/html/release/admin;
        cp -r /data/* /usr/share/nginx/html/release/admin"
    volumes:
      - web-data:/usr/share/nginx/html/release
  portal:
    image: hhoao/rare-earth-track-portal:${RARE_EARTH_TRACK_PORTAL_VERSION}
    depends_on:
      redis:
        condition: service_healthy
      mysql:
        condition: service_healthy
    volumes:
      - /data/uploads:/data/uploads
#    ports:
#      - ${RARE_EARTH_TRACK_PORTAL_PORT}:8889

  admin:
    image: hhoao/rare-earth-track-admin:${RARE_EARTH_TRACK_ADMIN_VERSION}
    depends_on:
      redis:
        condition: service_healthy
      mysql:
        condition: service_healthy
    volumes:
      - /data/uploads:/data/uploads
#    ports:
#      - ${RARE_EARTH_TRACK_ADMIN_PORT}:8888

  mysql:
    image: mysql:${MYSQL_VERSION}
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    mem_limit: ${MEM_LIMIT}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - mysql:/var/lib/mysql
      - mysql-files:/var/lib/mysql-files
      - mysql-config:/etc/mysql
    security_opt:
      - seccomp:unconfined
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  redis:
    image: redis:${REDIS_VERSION}
    command: redis-server
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 30

volumes:
  web-data:
    driver: local
  redis:
    driver: local
  mysql:
    driver: local
  mysql-files:
    driver: local
  mysql-config:
    driver: local
