version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0.1
    steps:
      - checkout
      - run: mvn -Dspring.profiles.active=test -Djasypt.encryptor.password=$JASYPT_PASSWORD test

workflows:
    version: 2
    build-and-test:
        jobs:
           - build-and-test



