version: 2.1

commands:
  diff-detect:
    parameters:
      changed:
        type: string
        default: "/"
        description: "改变的文件,可以使用正则表达式"
    steps:
      - attach_workspace:
          name: git-pre-version
          at: .
      - run: |
          info=$(git diff --summary HEAD^ | sed -n  '/<< parameters.changed >>/p')
          if [ ! "${info}" ];
          then
            circleci-agent step halt
          fi
    description: "判断git文件是否修改"

jobs:
  build-and-test:
    parameters:
      changed:
        type: string
        default: "/"
        description: "改变的文件,可以使用正则表达式"
      module-name:
        type: enum
        default: "rare-earth-track-admin"
        enum: [ "rare-earth-track-admin", "rare-earth-track-portal", "rare-earth-track-search" ]
    docker:
      - image: cimg/openjdk:17.0.1
      - image: cimg/redis:6.2.6
    steps:
      - checkout
      - diff-detect:
          changed: << parameters.module-name >>
      - restore_cache:
          keys:
            - v1-admin-dependencies-{{ checksum "<< parameters.module-name >>/pom.xml" }}
      - run:
          name: Admin package
          command: mvn -Dspring.profiles.active=test -Djasypt.encryptor.password=$JASYPT_PASSWORD
            -pl '<< parameters.module-name >>, rare-earth-track-common, rare-earth-track-mgb, rare-earth-track-security' package
      - store_test_results:
          name: Admin store test report
          path: << parameters.module-name >>/target/surefire-reports
      - save_cache:
          paths:
            - ~/.m2
          key: v1-admin-dependencies-{{ checksum "<< parameters.module-name >>/pom.xml" }}
      - persist_to_workspace:
          root: .
          paths:
            - << parameters.module-name >>/target
  docker-build:
    parameters:
      changed:
        type: string
        default: "/"
        description: "改变的文件,可以使用正则表达式"
      module-name:
        type: enum
        default: "rare-earth-track-admin"
        enum: [ "rare-earth-track-admin", "rare-earth-track-portal", "rare-earth-track-search" ]
      image:
        type: enum
        default: "hhoao/rare-earth-track-admin:1.0-SNAPSHOT"
        enum: [ "hhoao/rare-earth-track-admin:1.0-SNAPSHOT", "hhoao/rare-earth-track-portal:1.0-SNAPSHOT"]
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - diff-detect:
          changed: << parameters.module-name >>
      - attach_workspace:
          at: .
      - run:
          command:  |
            if [ ! -d ~/.docker ];
            then
              mkdir ~/.docker
            fi
            cat > ~/.docker/config.json \<< EOF
            {
              "auths": {
                "https://index.docker.io/v1/": {
                  "auth":"$DOCKER_AUTH"
                }
              }
            }
            EOF
      - run:
          name: Docker build admin image
          command: docker build -t << parameters.image >> << parameters.module-name >>
      - run:
          name: Docker push admin image
          command: docker push << parameters.image >>
  deploy:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - run: |
          ssh root@${SERVER_HOSTS} 
          ${SERVER_PASSWORD}
          cd /root/rare-earth-track/document/docker
          git pull github dev:dev
          docker compose -f rare-earth-track-env.yml up
          docker compose -f up
      - run: |
          echo $(git rev-parse HEAD) > git-pre-version
      - persist_to_workspace:
          name: git-pre-version
          root: .
          paths:
            - git-pre-version
workflows:
    build-and-test-and-deploy:
        jobs:
           - build-and-test:
               name: build-and-test-admin
               changed: rare-earth-track-admin\/src
               module-name: "rare-earth-track-admin"
           - build-and-test:
               name: build-and-test-portal
               changed: 'rare-earth-track-portal\/src'
               module-name: "rare-earth-track-portal"
           - build-and-test:
               name: build-and-test-search
               changed: 'rare-earth-track-search\/src'
               module-name: "rare-earth-track-search"
           - docker-build:
               name: docker-build-admin
               changed: rare-earth-track-admin\/src
               module-name: rare-earth-track-admin
               requires:
                 - build-and-test-admin
               filters:
                 branches:
                   only:
                     - master
           - docker-build:
               name: docker-build-portal
               changed: rare-earth-track-portal\/src
               module-name: rare-earth-track-portal
               requires:
                 - build-and-test-portal
               filters:
                 branches:
                   only:
                     - master
           - docker-build:
               name: docker-build-search
               changed: rare-earth-track-search\/src
               module-name: rare-earth-track-search
               requires:
                 - build-and-test-search
               filters:
                 branches:
                   only:
                     - master
           - deploy:
               requires:
                 - docker-build-portal
                 - docker-build-admin
                 - docker-build-search




