version: 2

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0.1
      - image: cimg/redis:6.2.6
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
#      - run:
#          name: Test
#          command: mvn -Dspring.profiles.active=test -Djasypt.encryptor.password=$JASYPT_PASSWORD test
#      - store_test_results:
#          name: Admin test report
#          path: rare-earth-track-admin/target/surefire-reports
#      - store_test_results:
#          name: Portal test report
#          path: rare-earth-track-portal/target/surefire-reports
      - run:
          name: Install
          command: mvn -DskipTests -pl  '!rare-earth-track-admin, !rare-earth-track-portal' install
      - run:
          name: Package
          command: mvn -DskipTests -pl  'rare-earth-track-admin, rare-earth-track-portal' package
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - persist_to_workspace:
          root: .
          paths:
            - rare-earth-track-portal/target
            - rare-earth-track-admin/target
  deploy:
    docker:
      - image: cimg/openjdk:17.0.1
    steps:
      - attach_workspace:
          at: .
      - run:
          command:  |
            if [ ! -d ~/.docker ];
            then
              mkdir ~/.docker
            fi
            cat > ~/.docker/config.json << EOF
            {
              "auths": {
                "https://index.docker.io/v1/": {
                  "auth":"$DOCKER_AUTH"
                }
              }
            }
            EOF
      - run:
          name: Docker build
          command: mvn -pl '!rare-earth-track-admin, !rare-earth-track-portal' docker:push
      - run:
          name: Docker Push
          command: mvn -pl 'rare-earth-track-admin, rare-earth-track-portal' docker:push

workflows:
    version: 2
    build-and-test-and-deploy:
        jobs:
           - build-and-test
           - deploy:
               requires:
                 - build-and-test
               filters:
                 branches:
                   ignore:
                     - dev




