version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/maven:3.8.6
    steps:
      - checkout
      - run: mvn -Dspring.profiles.active=test test

workflows:
    version: 2
    build-and-test:
        jobs:
           - build-and-test



